version: "3"
services:
  container_mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"

  container_user_flask_api:
    image: user_flask_api
    ports:
    - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql://root:root@127.0.0.1:3306/user_db'
      SECRET_KEY: 'testar2@'
    depends_on:
      - container_mysql

