version: "3"
services:
  container_mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"

  container_api_user:
    image: api_user
    ports:
    - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql://root:root@container_mysql:3306/user_db'
      SECRET_KEY: 'testar2@'
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - container_mysql

